// ... (previous content)
  gardenDockBasketCount: { color: FARM.playButtonShadow, fontSize: 16, fontWeight: '900' },
  gardenToolBtn: {
    width: 80, height: 80, borderRadius: 22, alignItems: 'center', justifyContent: 'center',
    borderWidth: 3, borderColor: '#7A4A14', ...SHADOWS.button,
  },
  gardenToolBtnSelected: { borderColor: FARM.cardHintBorder, borderWidth: 4 },
  gardenToolBtnLabel:    { color: '#F5DEB3', fontSize: 10, fontWeight: '800', textAlign: 'center', marginTop: 3 },
  gardenFieldPressablePortrait: { flex: 1, width: '100%', minHeight: 0, marginHorizontal: 0 },
  gardenInstructionText:  { color: '#D4EDAE', fontSize: 13, fontWeight: '800', textAlign: 'center', textShadowColor: 'rgba(0,0,0,0.35)', textShadowOffset: { width: 0, height: 1 }, textShadowRadius: 3 },
  gardenFieldPatch: {
    flex: 1, marginTop: 6, marginHorizontal: 8, marginBottom: 4,
    borderRadius: 16, borderWidth: 3, borderColor: '#2E5A1A',
    backgroundColor: '#4A7830', paddingHorizontal: 8, paddingVertical: 10, ...SHADOWS.card,
  },
  gardenPlotGridColumn: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  gardenGridHitArea:    { alignSelf: 'center' },
  gardenGridRow:        { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', flexWrap: 'nowrap' },
  gardenPlotWrap:       { borderRadius: 14, ...SHADOWS.card },
  gardenPlotWrapLocked: { shadowOpacity: 0.12, elevation: 2 },
  gardenPlot: {
    borderRadius: 12, alignItems: 'center', justifyContent: 'center',
    overflow: 'hidden', borderWidth: 2, borderColor: '#C8A064',
  },
  gardenPlotEmpty:        { borderStyle: 'dashed', borderColor: '#A07840', borderWidth: 2 },
  gardenLockedPreviewImage: { opacity: 0.35, position: 'absolute' },
  gardenLockedVeil:       { backgroundColor: 'rgba(0,0,0,0.44)', borderRadius: 12 },
  gardenLockedIconWrap:   { position: 'absolute', alignItems: 'center', justifyContent: 'center', bottom: '14%' },
  gardenUnlockGlow: {
    ...StyleSheet.absoluteFillObject, margin: -3, borderRadius: 18, borderWidth: 3,
    shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.75, shadowRadius: 12, elevation: 10,
  },
  gardenPlotHovered: {
    borderWidth: 3, borderColor: FARM.cardHintBorder,
    shadowColor: FARM.cardHintBorder, shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.55, shadowRadius: 10, elevation: 8,
  },
  gardenPlotCropImage: { marginTop: 2 },
  gardenWinBackdrop: { flex: 1, backgroundColor: 'rgba(15,23,42,0.45)', alignItems: 'center', justifyContent: 'center', padding: 24 },
  gardenWinCard: {
    width: '100%', maxWidth: 340, borderRadius: 24, paddingVertical: 28, paddingHorizontal: 22,
    alignItems: 'center', borderWidth: 3, borderColor: FARM.cardMatchedBorder, ...SHADOWS.card,
  },
  gardenWinTitle: { fontSize: 26, color: FARM.headerTitleColor, textAlign: 'center', marginBottom: 10 },
  gardenWinSub:   { fontSize: 15, color: FARM.subtitleColor, textAlign: 'center', marginBottom: 22, lineHeight: 22 },
  gardenWinBtn:   { paddingVertical: 14, paddingHorizontal: 36, borderRadius: 18, borderWidth: 3, borderColor: FARM.playButtonShadow, ...SHADOWS.button },
  gardenWinBtnText: { fontSize: 17, color: FARM.playButtonText, fontWeight: '800' },
  gardenFlyOverlay: { position: 'absolute', minWidth: 56, minHeight: 56, alignItems: 'center', justifyContent: 'center', zIndex: 99 },
  gardenDragFloat:  { position: 'absolute', width: 64, height: 64, alignItems: 'center', justifyContent: 'center', zIndex: 999 },
  // Milestone Modal Styles (Step 4)
  gardenStarsContainer: { flexDirection: 'row', justifyContent: 'center', marginBottom: 15, marginTop: 5 },
});
